name: DevAthlon_2
version: 1.0.0
main: de.nonamelabs.devathlon.Plugin_MineTime
commands:
  startgame:
    description: Startet das Spiel
    usage: /startgame <rooms> <time>
  resetRooms:
    description: Setzt alle Raeume zurueck
    usage: /resetRooms
  stopGame:
    description: Stoppt das Spiel
    usage: /stopGame
  selector:
    description: Gibt dem Spieler das Auswahl Item
    usage: /selector